### PR TITLE
finishing interactive sim and adding SBP

### PR DESCRIPTION
**Pull request by SylLutze**
Hi all - adding in SBP. Everything looks quite similar for causes and exposure. I built out the work in the interactive sim and that is all validating now as well.

### CODE REVIEW

**Comment by stevebachmeier** [comment]
What is the proper way to review these PRs? Do I need to pull the branch and just look at the notebooks holistically?

**Comment by aflaxman** [comment]
You can view the notebook in GitHub, if you click just the right way on the PR, and there is some sort of plug-in that Zeb has used that lets us look at notebook diffs, but even with that, I find notebooks in PR very hard to review.

**Review by aflaxman — APPROVED** [review]
If you add .ipynb_checkpoints to the .gitignore file, you will have an easier time not including these additional notebooks, e.g. .ipynb_checkpoints/Interactive_Model2_VV-checkpoint.ipynb

Was Untitled.ipynb included intentionally?  A more descriptive name will help future readers.

What is up with the validations that spike at age 40?? (e.g. this fromInteractive_Model2_VV.ipynb):

image

**Comment by SylLutze** [comment]
Thanks Abie! I will work on the .gitignore file. I hadn't intended to include the 'untitled' it was basically just a play space for me with no real work in it. 

For the spike - there are 2 outliers, both are 40 year old women with super weird values that are throwing things. I'll follow-up with Steve about these.

**Pull request merged**
